p8105_mtp_rw3033
================

# Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(rvest)
```

    ## 
    ## Attaching package: 'rvest'
    ## 
    ## The following object is masked from 'package:readr':
    ## 
    ##     guess_encoding

``` r
library(httr)

# Import Data
rental_df = read_csv("~/Desktop/BIST8105/HW/p8105_mpt_rw3033/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",
  na = c("NA", ".", ""))|>
  janitor::clean_names()
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
url = "https://p8105.com/data/zip_codes.html"
zip_html = read_html(url)
```

``` r
library(dplyr)

zip_df = zip_html |> 
  html_table()|>
  first() |>
  janitor::clean_names()

# Create borough variable based on county names
zip_df = zip_df |>
  mutate(borough = case_when(
    county == "New York" ~ "Manhattan",
    county == "Kings" ~ "Brooklyn",
    county == "Queens" ~ "Queens",
    county == "Bronx" ~ "The Bronx",
    county == "Richmond" ~ "Staten Island"))
```

``` r
library(dplyr)
library(stringr)

# # Merging the NYC Rental and ZIP code data
merged_df = rental_df |>
  left_join(zip_df, by = c("region_name" = "zip_code"))|>
  select(-state_fips, -county_code,-county_fips,-region_id, -size_rank,-metro,-county_name,-region_type,-state_name,-state,-city)
```

``` r
# Get the total number of observations
total_observations = nrow(merged_df)

# Get the number of unique ZIP codes
unique_zip_codes = merged_df |> 
  pull(region_name) |>
  n_distinct()

# Get the number of unique neighborhoods
unique_neighborhoods = merged_df |>
  pull(neighborhood) |>
  n_distinct()

total_observations
```

    ## [1] 151

``` r
unique_zip_codes
```

    ## [1] 149

``` r
unique_neighborhoods
```

    ## [1] 43

There are total 151 observations exist in the merged data. There are 149
unique ZIP codes. There are 43 unique neighborhoods. The
total_observations should match unique_zip_codes, but in this case there
are 2 more observations. Hence, there must be duplication in zip code in
the merged data.

``` r
# Find the duplicated zip code
duplicated_zip_code = merged_df |>
  filter(duplicated(region_name))|>
  select(region_name)

duplicated_zip_code
```

    ## # A tibble: 2 × 1
    ##   region_name
    ##         <dbl>
    ## 1       10463
    ## 2       11201

“10463” and “11201” are the two repetitive zip codes. These zip codes
exist because the two regions are connected, causing them to share the
same zip code. Therefore, I will delete the rows repetitive zip code.

``` r
# Delete the rows repetitive zip code
clean_merged_df = merged_df |>
  filter(!(region_name == 10463 & borough == "Manhattan") & 
         !(region_name == 11201 & borough == "Manhattan"))

# Get the total number of observations
clean_total_observations = nrow(clean_merged_df)

# Get the number of unique ZIP codes
clean_unique_zip_codes = clean_merged_df |> 
  pull(region_name) |>
  n_distinct()

# Get the number of unique neighborhoods
clean_unique_neighborhoods = clean_merged_df |>
  pull(neighborhood) |>
  n_distinct()

clean_merged_df = clean_merged_df |>
  pivot_longer(
    x2015_01_31:x2024_08_31,
    names_to = "date", 
    names_prefix = "x",
    values_to = )
```

After the data cleaning: There are total 149 observations exist in the
merged data. There are 149 unique ZIP codes. There are 43 unique
neighborhoods. After the data cleaning, the total_observations matches
unique_zip_codes.

``` r
# Import and clean the 2023 US Housing data
housing_df = read_csv("~/Desktop/BIST8105/HW/p8105_mpt_rw3033/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month_2023.csv",
  na = c("NA", ".", ""))|>
  janitor::clean_names()|>
  select(-region_id,-size_rank,-metro,-county_name,-region_type,-state_name,-state,-city)
```

    ## Rows: 26338 Columns: 21
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr  (7): RegionName, RegionType, StateName, State, City, Metro, CountyName
    ## dbl (14): RegionID, SizeRank, 2023-01-31, 2023-02-28, 2023-03-31, 2023-04-30...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

For data cleaning, I kept only zip code(region name).

# Problem 2

There are 116 months between January 2015 and August 2024, but in the
NYC Rental dataset, many ZIP codes have fewer than 116 observations.
This could be because the house may not have been rented every month.

``` r
# Get the total number of ZIP codes in zip_df
zip_zip_observations = nrow(zip_df)

# Get the total number of ZIP codes in rental_df
rental_zip_observations = nrow(rental_df)

# Get the number of ZIP codes in zip_df but not rental_df
missing_zip_rental = anti_join(zip_df, rental_df, by = c("zip_code" = "region_name"))
missing_zip_rental = nrow(missing_zip_rental)

# Get the number of ZIP codes in zip_df but not rental_df
missing_zip_zip = anti_join(rental_df, zip_df, by = c("region_name" = "zip_code"))
missing_zip_zip = nrow(missing_zip_zip)

zip_zip_observations
```

    ## [1] 322

``` r
rental_zip_observations
```

    ## [1] 149

``` r
missing_zip_rental
```

    ## [1] 171

``` r
missing_zip_zip
```

    ## [1] 0

The total number of ZIP codes in zip_df is 322. The total number of ZIP
codes in rental_df is 149. The number of ZIP codes in zip_df but not
rental_df is 171 The number of ZIP codes in zip_df but not rental_df 0
The NYC rental dataset has fewer ZIP codes than the ZIP code dataset,
which could be because not all regions in NYC have housing rentals.
